### ISSUE TITLE
Document and describe types of deployments Azavea commonly engages in

### ISSUE THREAD

**Issue by moradology** [azavea/kubernetes-deployment#2]
Different types of projects are naturally going to be better or worse for management through k8s. For example (and looking to the clear cut cases at the extremes), it is likely unwise to manage a static application with k8s whereas a process with heavy asynchronous workflows and the need for a distributed set of resources (zookeeper, Kafka, etc) is more likely to benefit from deployment through k8s. The first step is to describe the deployment-scenarios we actually engage in.

So: what types of deployment do we do at Azavea?

**Comment by rajadain** [comment]
I've put me thoughts in this Google Doc: https://docs.google.com/document/d/18FRR6xiFEOks_l2qP63dtgrVFh2ZPKxqFgCr_gGY4ic/edit?usp=sharing. It's far from complete, hope I can elicit additional feedback and ideas to incorporate.

**Comment by jpolchlo** [comment]
@rajadain Can we close this out now, even if the document isn't complete?  It's increasingly clear that k8s is not going to provide a one-size-fits-all solution for our common deployments.  At least not yet.  We can revisit in the future.

**Comment by rajadain** [comment]
Agreed. Closing for now.
