### ISSUE TITLE
howto: local cluster

### ISSUE THREAD

**Issue by moradology** [azavea/kubernetes-deployment#3]
A useful deliverable for both educational purposes and for first steps in this working group would be documentation of paths to locally running a cluster. Mac and linux (we can probably just assume Ubuntu for this purpose) steps are desirable. Screenshots and links to external resources are fair game

**Comment by jpolchlo** [comment]
Given that there are many such documents on the web to choose from, I'm closing this issue, since we'd be better served simply linking to a good external source, and not spending any time creating one of our own.
